# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d67d77809656fc83c6cb099a06adf1883decc22f27f5ed5b11d14673f0e95d4daf81d631e308691479d417874e5f17e2189bf9e9dbee9f04e73ae47fecfcd5ec

test:
  secret_key_base: 5318dac330ea7e4c0666f9c5954f023a86efca5863f1b6f6b78607d79762259d2604a847e86a249413723199422768b4f986834f5745f6b9e12d7a72fc87d049

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
